apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.logging.syncWave | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: openshift-logging
    server: https://kubernetes.default.svc
  source:
    repoURL: {{ .Values.global.repo.url }}
    path: charts/elasticsearch
    targetRevision: {{ .Values.global.repo.branch }}
    helm:
      releaseName: logging
{{- with .Values.logging.elastic.values }}
      values: |-
{{- toYaml . | nindent 8 }}
{{- end }}
      parameters:
      - name: fullnameOverride
        value: logging
      - name: ingress.hostName
        value: logging
      - name: ingress.baseDomain
        value: {{ .Values.global.baseDomain }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
